name: PR Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      ###########################################
      ## Checkout
      ###########################################
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kdevkr/platform
          token: ${{ secrets.PLATFORM_TOKEN }}
          ref: main
      - name: Checkout submodules
        run: |
          git submodule update --init monorepo
          cd monorepo/
          git checkout ${{ github.event.pull_request.head.sha }}

      ###########################################
      ## Set up Node
      ###########################################
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      ###########################################
      ## Build and ESLint
      ###########################################
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Install dependencies
        run: |
          cd monorepo/frontend
          pnpm install
          eslint --ext .js,.vue -f checkstyle src/ | reviewdog -f=checkstyle -name="eslint" -reporter=github-pr-check
#      - name: Build with vite
#        run: |
#          cd monorepo/frontend
#          pnpm run build