name: check:eslint

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      ###########################################
      ## Checkout
      ###########################################
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      ## Set up Node
      ###########################################
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          package_json_file: './monorepo/frontend/package.json'
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      ###########################################
      ## ESLint
      ###########################################
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -version
          cd frontend/
          pnpm install
          npx --no-install -c "eslint -f rdjson ./src/" | reviewdog -f=rdjson -reporter=github-pr-check