name: pr-checks

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        java: [ 17 ]

    steps:
      ###########################################
      ## Checkout
      ###########################################
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      ## Set up Java
      ###########################################
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin # (https://github.com/marketplace/actions/setup-java-jdk#supported-distributions)
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: "gradle"

      ###########################################
      ## Checkstyle
      ###########################################
      - name: Run checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          checkstyle_config: google_checks.xml


  eslint:
    name: eslint
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        node: [ 18 ]

    steps:
      ###########################################
      ## Checkout
      ###########################################
      - name: Checkout repository
        uses: actions/checkout@v4

      ###########################################
      ## Set up Node
      ###########################################
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          package_json_file: './frontend/package.json'
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      ###########################################
      ## ESLint
      ###########################################
      - name: Install dependencies
        run: pnpm --prefix frontend install
      - name: install eslint
        run: pnpm install -g eslint
      - name: eslint with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          eslint_flags: "--ext .js,.vue ./frontend/src"